all:
	cp AS.h AI/AS.h
	cp BFS.h AI/BFS.h
	cp DFS.h AI/DFS.h
	cp Game.cpp AI/Game.cpp
	cp Game.h AI/Game.h
	cp IDDF.h AI/IDDF.h
	cp main.cpp AI/main.cpp
	cp Print.cpp AI/Print.cpp
	cp Print.h AI/Print.h
	cp ReadFile.cpp AI/ReadFile.cpp
	cp ReadFile.h AI/ReadFile.h
